# Generated by Django 5.0.6 on 2024-05-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=10)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('book_detail', models.TextField(max_length=500)),
            ],
        ),
    ]
