# Generated by Django 5.0.6 on 2024-05-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapi2', '0002_book_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
    ]
